/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROG_H_RPCGEN
#define _PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int String_len;
	char *String_val;
} String;

#define COMMANDPROG 0x20000008
#define COMMANDVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXECCOMMAND 1
extern  String * execcommand_1(char **, CLIENT *);
extern  String * execcommand_1_svc(char **, struct svc_req *);
extern int commandprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXECCOMMAND 1
extern  String * execcommand_1();
extern  String * execcommand_1_svc();
extern int commandprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_String (XDR *, String*);

#else /* K&R C */
extern bool_t xdr_String ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROG_H_RPCGEN */
